"""
stub file for rn.py
"""

from numpy import ndarray
from typing import Tuple


class RN:
    PERMITTED_PARAMETERS = ...  # type: tuple
    ARRAY_SIZES = ...  # type: tuple
    ARRAY_DIM = ...  # type: int
    PERMITTED_UNITS = ...  # type: tuple

    array = ...  # type: ndarray
    index = ...  #type: int or RN

    def __init__(self, array: ndarray, index: int or RN=1): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def num(self) -> ndarray: return
    @property
    def den(self) -> ndarray: return
    def __validate_array(self, array: ndarray) -> None: ...
    def __validate_den(self, array: ndarray) -> None: ...
    def __validate_index(self, index: int or RN) -> None: ...
    def __validate_array_type(self, array: ndarray) -> None: ...
    def __validate_array_sizes_conformity(self, array: ndarray) -> None: ...
    def __validate_array_data_types(self, array: ndarray) -> None: ...
    @staticmethod
    def __reduce(array: array, index: int or RN) -> Tuple[ndarray, int or RN]: ...
